### ISSUE TITLE
Plans for per player whitelist?

### ISSUE THREAD

**Issue by starryfae** [embeddedt/ApatheticMobsReborn#1]
The original had a command for server operators to add/remove players to a whitelist to have the mobs attack them, I'm working on a pack where difficulty is a choice and this implementation would be perfect :)

**Comment by embeddedt** [comment]
Thanks for opening an issue!

At the moment I've opted not to implement any mod platform-specific semantics like commands as I'm trying to avoid needing to write Forge and Fabric-specific code. However, would a player blacklist/whitelist option in the mod config file be good enough for your purposes?

**Comment by starryfae** [comment]
That would be even better, I was unsure what would be easier to implement

Thank you so much for considering my suggestion c:

**Comment by embeddedt** [comment]
Implemented in 1.2.0. I will upload the builds to CurseForge and attach them here for you in the meantime.

[mod.zip](https://github.com/embeddedt/ApatheticMobsReborn/files/7585612/mod.zip)

Let me know if you have any issues! The config should be self-explanatory.

```toml
playerList = ["50e3702d-f577-3e44-8b3c-fb2dc8cfae65", "another UUID here", "and so forth"]
```

**Comment by embeddedt** [comment]
By the way, if you end up making your pack public, let me know and I'd potentially be willing to advertise it on the mod page. It doesn't get much traffic at all compared to my Create mod, since most of the community does not appreciate apathetic mode at all, but I'd be happy to see it used in a decently popular modpack.

**Comment by starryfae** [comment]
Oh for sure!! It will be awhile, perfectionism is definitely a big hurdle I'm going through right now. 

Thank you for the blacklist implementation! 

I love Peaceful mode mods, this mod in particular allows the player to experience hunger mechanics and health drops without worrying about being spooked or blown up

In fact I just spent a few hours trying to create a Fabric mod that overrides the infinite exhaustion regen in peaceful mode, but I'm still new to programming and not just making kubejs or crafttweaker scripts

**Comment by starryfae** [comment]
Both Fabric & Forge configs are working great!

**Comment by embeddedt** [comment]
Since this feature's been implemented for a while, I'll be closing this issue now, however my offer still stands if/when you're done. :slightly_smiling_face:
