### ISSUE TITLE
[Bug?] Mod seems to affect passive mobs

### ISSUE THREAD

**Issue by pouchrat** [embeddedt/ApatheticMobsReborn#3]
I have another mod that causes passive mobs to flee from the player, but with this mod installed they seem not to notice me until I hit them (with revenge on). (With revenge off, they don't panic.)

Though this may be intended/wanted behavior, since it does make it easier to deal with rabbits.

**Comment by embeddedt** [comment]
> this may be intended/wanted behavior, since it does make it easier to deal with rabbits.

Not intended. My design strategy is to make a better peaceful mode. Since rabbits are not hostile they shouldn't stop fleeing the player, and neither should other passive mobs. Thanks for the report.

**Comment by embeddedt** [comment]
Could you let me know the name of the other mod you have installed (so that I can test this easier)?

**Comment by pouchrat** [comment]
Dragon Survival! The mobs only flee from you when you're a dragon, though.

The fastest way to become a dragon is to start in creative mode, set down a "stone dragon altar" and right-click it. You can choose any dragon, and then hit save and switch to survival mode and passive animals should be afraid of you.

Edit: Actually I think there are commands, too, but I don't know them off the top of my head.

**Comment by embeddedt** [comment]
Thanks. This is fixed in 1.5.0, the mobs will run away as in vanilla.
