### ISSUE TITLE
A few vanilla mobs aren't affected

### ISSUE THREAD

**Issue by Apellonyx** [embeddedt/ApatheticMobsReborn#4]
With "apatheticmobsreborn-1.6.0.jar" for Fabric MC 1.19, hoglins and zoglins still attack with the mod installed. Adding phantoms to the blacklist in the config file doesn't affect their behavior (they still don't attack the player). All of these issues occur with the "takeRevenge" config option as true, but I didn't test if it changes when false.

**Comment by embeddedt** [comment]
Please try 1.6.2 and let me know if it fixes your issues. I could not reproduce the zoglin issue but the other two are fixed.

**Comment by Apellonyx** [comment]
Tested 1.6.2, and all of the issues seem to be resolved, including the zoglin. Thanks!
